//
//  positions.h
//  pbInterface
//
//  Created by Brian Turnbull on 9/25/15.
//
//

#ifndef positions_h
#define positions_h

#define PREVIEW_PHOTO_WIDTH 900
#define PREVIEW_PHOTO_HEIGHT 600
#define GUTTER 30
#define HEADING_Y 100
#define TEXT_Y HEADING_Y + 30
#define PREVIEW_X GUTTER
#define PREVIEW_Y TEXT_Y + 20
#define PHOTOBAR_X GUTTER + PREVIEW_PHOTO_WIDTH + 10
#define PHOTOBAR_Y 55
#define FINAL_PHOTO_X GUTTER
#define FINAL_PHOTO_Y 140
#define FINAL_PHOTO_WIDTH 1200
#define SHARE_URL_X GUTTER
#define SHARE_URL_Y FINAL_PHOTO_Y + 500
#define SHARE_TEXT_X GUTTER
#define SHARE_TEXT_Y SHARE_URL_Y + 45
#define PHOTOBAR_PHOTO_WIDTH 300
#define PHOTOBAR_PHOTO_HEIGHT 225
#define PHOTOBAR_MARGIN 10
#define LOADING_W 50
#define LOADING_H 50
#define PREVIEW_CENTER_X (PREVIEW_PHOTO_WIDTH/2 + PREVIEW_X)
#define PREVIEW_CENTER_Y (PREVIEW_PHOTO_HEIGHT/2 + PREVIEW_Y)
#define LOADING_X (PREVIEW_CENTER_X - LOADING_W/2)
#define LOADING_Y (PREVIEW_CENTER_Y - LOADING_H/2)
#define COUNTDOWN_X (PREVIEW_CENTER_X - 80)
#define COUNTDOWN_Y PREVIEW_CENTER_Y

#endif /* positions_h */
