#!/bin/sh
#/etc/init.d/photobooth
# Based off of http://www.slidequest.com/q/70ang

WORKING_DIR=/opt/photobooth/embedded

export PATH=$PATH:/usr/local/bin
export NODE_PATH=$NODE_PATH:/usr/local/lib/node_modules

case "$1" in
	start)
	cd /opt/photobooth/embedded
	. secrets/env/prod.sh
	cd -
	NODE_ENV=production DEBUG=* exec forever start -u pb-prod --sourceDir=$WORKING_DIR --workingDir=$WORKING_DIR -a -l $WORKING_DIR/logs/forever.main.log -o $WORKING_DIR/logs/main.out.log -e $WORKING_DIR/logs/main.err.log main.js
	;;
	
	stop)
	forever stop --killSignal=SIGNINT pb-prod
	;;
	
	kill)
	forever stop --killSignal=SIGKILL pb-prod
	killall interface
	killall interface_debug
	;;
	
	*)
	echo "Usage: /etc/init.d/photobooth {start|stop|kill}"
	exit 1
	;;
esac
exit 0
